services:
  composer:
    restart: always
    env_file:
      - ../composer/.env
    environment:
      - TZ=UTC
      - STAGE=prod
    build:
      context: ../composer
      target: prod
    volumes:
      - astro_articles:/shared/article:rw
    networks:
      - bitpulse

  astro:
    restart: always
    env_file:
      - ../astro/.env
    environment:
      - TZ=UTC
      - STAGE=prod
    build:
      context: ../astro
      target: prod
    volumes:
      - astro_articles:/assets/src/content/article
      - astro_dist:/assets/dist
    networks:
      - bitpulse

  gateway:
    restart: always
    # Enables the web UI and tells Traefik to listen to docker
    command: --providers.docker=true --ping=true --log=true --log.level="TRACE" --accesslog=true --tracing=true
    ports:
      # The HTTP (AND S) port
      - "8000:80"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=UTC
      - STAGE=prod
    build:
      context: ../gateway
      target: prod
    networks:
      - bitpulse

  nginx:
    restart: always
    build:
      context: ../nginx
      target: prod
    volumes:
      - astro_dist:/usr/share/nginx/html:rw
    environment:
      - TZ=UTC
      - STAGE=prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`bitpulse.online`) && PathPrefix(`/`)"
    networks:
      - bitpulse

networks:
  bitpulse:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16
          gateway: 172.22.0.1

volumes:
  astro_articles:
  astro_dist:
