services:
  composer:
    restart: always
    env_file:
      - ../composer/.env
    environment:
      - TZ=UTC
      - STAGE=dev
    build:
      context: ../composer
      target: dev
    volumes:
      - ../composer/assets:/assets
      - ../astro/assets/src/content/article:/shared/article:rw
    networks:
      - bitpulse

  astro:
    restart: always
    env_file:
      - ../astro/.env
    environment:
      - TZ=UTC
      - STAGE=dev
    build:
      context: ../astro
      target: dev
    volumes:
      - ../astro/assets:/assets
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.astro.rule=PathPrefix(`/astro`)"
      - "traefik.http.middlewares.astro-set-header.headers.customrequestheaders.X-Forwarded-Host=${DOMAIN}"
      - "traefik.http.middlewares.astro-set-header.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.astro.middlewares=astro-set-header"
    networks:
      - bitpulse

  gateway:
    restart: always
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker=true --ping=true --log=true --log.level="TRACE" --accesslog=true --tracing=true
    ports:
      # The HTTP (AND S) port
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=UTC
      - STAGE=dev
    build:
      context: ../gateway
      target: dev
    networks:
      - bitpulse

  nginx:
    restart: always
    build:
      context: ../nginx
      target: dev
    volumes:
      - ../nginx/conf:/etc/nginx/conf.d:rw
      - ../astro/assets/dist:/usr/share/nginx/html:rw
    environment:
      - TZ=UTC
      - STAGE=dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=PathPrefix(`/`)"
    networks:
      - bitpulse

networks:
  bitpulse:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16
          gateway: 172.22.0.1
